AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ScheduleManager:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ScheduleManager
      Runtime: python3.9
      Timeout: 10
      Handler: app.handler
      CodeUri: ./src
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Hook:
          Type: Api
          Properties:
            Path: /hook
            Method: POST
      Environment:
        Variables:
          OPENAI_API_KEY: Dummy
          SLACK_BOT_TOKEN: Dummy
          